appname = "crew"
usage = "DevOps RBCA service"
version = "0.0.1"
author = "Meaglith Ma"
email = "genedna@gmail.com "

# include runtime.conf
runmode = "dev"

listenmode = "http"
httpscertfile = "cert/containerops/containerops.sh.crt"
httpskeyfile = "cert/containerops/containerops.sh.key"

[log]
filepath = "log/backend.log"
level = "info"

[database]
driver = "mysql"
uri = "root:root@tcp(0.0.0.0:3306)/crew?charset=utf8&parseTime=True&loc=Asia%2FShanghai"
